### ISSUE TITLE
gvault

### ISSUE THREAD

**Issue by sourcec0de** [GoogleCloudPlatform/k8s-cloudkms-plugin#1]
This isn't really the appropriate place to be posting this. But I figured I would make someone aware of a project I'm working on that uses KMS to encrypt secrets to be stored in source control which can also sync with K8s.

https://github.com/sourcec0de/gvault

I'm curious how I could get my tool to play well with this plugin :)

**Comment by immutableT** [comment]
Hey @sourcec0de 
Sorry for a slow response, I did not have proper notification setup on this repo.
Great job on gvault !!!

With respect to gvault playing nice with this plugin - I think it will just happen.
When gvault syncs to K8S secrets arrive in clear text (wrapped in TLS) and will be deposited to ETCD encrypted via the plugin.

It may be possible to send secrets in an encrypted form from gvault to K8S and let the plugin decrypt them when PODs request (some work would be needed here on K8S side). This assumes that gvault and plugin will have access the the same keys.
Not sure if it will be worth the effort since PODs would need secrets in clear text anyway. In other words, we could consider securing the ADD/EDIT calls.
Let me know what you think.
